class SaintModel {
  final String name;
  final String bio;
  final String prayer;
  final bool isMajorFeast;

  const SaintModel({
    required this.name,
    required this.bio,
    required this.prayer,
    this.isMajorFeast = false,
  });
}

class SaintsDatabase {
  // ==============================================================================
  // 1. PUBLIC API: GET SAINT FOR DATE
  // ==============================================================================
  static SaintModel getSaint(int month, int day) {
    final String key = "$month-$day";

    // 1. Identify the Saint Name for today
    final String saintName = _calendar[key] ?? "Holy Saint of the Day";

    // 2. Try to fetch detailed curated content (Bio/Prayer)
    if (_curatedSaintsData.containsKey(saintName)) {
      return _curatedSaintsData[saintName]!;
    }

    // 3. PRODUCTION FALLBACK:
    // If we haven't manually written the bio yet, generate a respectful one dynamically.
    // This ensures the app never shows "Loading..." or empty text.
    return SaintModel(
      name: saintName,
      bio:
          "Today the Church honors $saintName, whose life stands as a testament to the enduring power of faith. Through dedication and witness to the Gospel, $saintName remains an inspiration to Christians around the world.",
      prayer:
          "Almighty God, who called $saintName to follow Christ, grant that by their intercession and example, we may walk in Your way and find our home in Your eternal kingdom. Amen.",
      isMajorFeast: false,
    );
  }

  // ==============================================================================
  // 2. THE COMPLETE LITURGICAL CALENDAR (365 Days)
  // ==============================================================================
  static final Map<String, String> _calendar = {
    // JANUARY
    "1-1": "Mary, Mother of God",
    "1-2": "St. Basil the Great",
    "1-3": "The Holy Name of Jesus",
    "1-4": "St. Elizabeth Ann Seton",
    "1-5": "St. John Neumann",
    "1-6": "St. André Bessette",
    "1-7": "St. Raymond of Penyafort",
    "1-8": "St. Angela of Foligno",
    "1-9": "St. Adrian of Canterbury",
    "1-10": "St. Gregory of Nyssa",
    "1-11": "St. Theodosius",
    "1-12": "St. Marguerite Bourgeoys",
    "1-13": "St. Hilary of Poitiers",
    "1-14": "St. Felix of Nola",
    "1-15": "St. Paul the Hermit",
    "1-16": "St. Berard and Companions",
    "1-17": "St. Anthony the Abbot",
    "1-18": "St. Margaret of Hungary",
    "1-19": "St. Fabian",
    "1-20": "St. Sebastian",
    "1-21": "St. Agnes",
    "1-22": "St. Vincent of Saragossa",
    "1-23": "St. Marianne Cope",
    "1-24": "St. Francis de Sales",
    "1-25": "Conversion of St. Paul",
    "1-26": "St. Timothy and St. Titus",
    "1-27": "St. Angela Merici",
    "1-28": "St. Thomas Aquinas",
    "1-29": "St. Gildas",
    "1-30": "St. Hyacintha Mariscotti",
    "1-31": "St. John Bosco",

    // FEBRUARY
    "2-1": "St. Brigid of Ireland",
    "2-2": "Presentation of the Lord",
    "2-3": "St. Blaise",
    "2-4": "St. Joan of Valois",
    "2-5": "St. Agatha",
    "2-6": "St. Paul Miki",
    "2-7": "St. Colette",
    "2-8": "St. Josephine Bakhita",
    "2-9": "St. Apollonia",
    "2-10": "St. Scholastica",
    "2-11": "Our Lady of Lourdes",
    "2-12": "St. Apollonius",
    "2-13": "St. Catherine de Ricci",
    "2-14": "St. Valentine",
    "2-15": "St. Claude de la Colombière",
    "2-16": "St. Juliana",
    "2-17": "Seven Holy Founders",
    "2-18": "St. Simeon",
    "2-19": "St. Conrad",
    "2-20": "St. Jacinta Marto",
    "2-21": "St. Peter Damian",
    "2-22": "Chair of St. Peter",
    "2-23": "St. Polycarp",
    "2-24": "St. Matthias",
    "2-25": "St. Walburga",
    "2-26": "St. Paula",
    "2-27": "St. Gabriel of Our Lady of Sorrows",
    "2-28": "St. Oswald",

    // MARCH
    "3-1": "St. David of Wales",
    "3-2": "St. Agnes of Bohemia",
    "3-3": "St. Katharine Drexel",
    "3-4": "St. Casimir",
    "3-5": "St. John Joseph of the Cross",
    "3-6": "St. Colette",
    "3-7": "Sts. Perpetua and Felicity",
    "3-8": "St. John of God",
    "3-9": "St. Frances of Rome",
    "3-10": "St. John Ogilvie",
    "3-11": "St. Constantine",
    "3-12": "St. Innocent I",
    "3-13": "St. Leander",
    "3-14": "St. Maximilian",
    "3-15": "St. Louise de Marillac",
    "3-16": "St. Clement Mary Hofbauer",
    "3-17": "St. Patrick",
    "3-18": "St. Cyril of Jerusalem",
    "3-19": "St. Joseph, Husband of Mary",
    "3-20": "St. Cuthbert",
    "3-21": "St. Serapion",
    "3-22": "St. Nicholas Owen",
    "3-23": "St. Turibius",
    "3-24": "St. Oscar Romero",
    "3-25": "The Annunciation",
    "3-26": "St. Margaret Clitherow",
    "3-27": "St. Rupert",
    "3-28": "St. Catherine of Bologna",
    "3-29": "St. Berthold",
    "3-30": "St. Peter Regalado",
    "3-31": "St. Benjamin",

    // APRIL
    "4-1": "St. Hugh",
    "4-2": "St. Francis of Paola",
    "4-3": "St. Richard",
    "4-4": "St. Isidore of Seville",
    "4-5": "St. Vincent Ferrer",
    "4-6": "St. Crescentia",
    "4-7": "St. John Baptist de La Salle",
    "4-8": "St. Julie Billiart",
    "4-9": "St. Casilda",
    "4-10": "St. Magdalen",
    "4-11": "St. Stanislaus",
    "4-12": "St. Teresa of Los Andes",
    "4-13": "St. Martin I",
    "4-14": "St. Lidwina",
    "4-15": "St. Caesar de Bus",
    "4-16": "St. Bernadette Soubirous",
    "4-17": "St. Benedict Joseph Labre",
    "4-18": "St. Perfectus",
    "4-19": "St. Gianna Molla",
    "4-20": "St. Conrad",
    "4-21": "St. Anselm",
    "4-22": "St. Adalbert",
    "4-23": "St. George",
    "4-24": "St. Fidelis",
    "4-25": "St. Mark the Evangelist",
    "4-26": "St. Pedro",
    "4-27": "St. Zita",
    "4-28": "St. Peter Chanel",
    "4-29": "St. Catherine of Siena",
    "4-30": "St. Pius V",

    // MAY
    "5-1": "St. Joseph the Worker",
    "5-2": "St. Athanasius",
    "5-3": "Sts. Philip and James",
    "5-4": "St. Florian",
    "5-5": "St. Hilary of Arles",
    "5-6": "St. Dominic Savio",
    "5-7": "St. Rose Venerini",
    "5-8": "St. Peter of Tarentaise",
    "5-9": "St. Pachomius",
    "5-10": "St. Damien of Molokai",
    "5-11": "St. Ignatius of Laconi",
    "5-12": "Sts. Nereus and Achilleus",
    "5-13": "Our Lady of Fatima",
    "5-14": "St. Matthias",
    "5-15": "St. Isidore the Farmer",
    "5-16": "St. Simon Stock",
    "5-17": "St. Paschal Baylon",
    "5-18": "St. John I",
    "5-19": "St. Ivo",
    "5-20": "St. Bernardine of Siena",
    "5-21": "St. Cristobal",
    "5-22": "St. Rita of Cascia",
    "5-23": "St. Gregory VII",
    "5-24": "Mary Help of Christians",
    "5-25": "St. Bede",
    "5-26": "St. Philip Neri",
    "5-27": "St. Augustine of Canterbury",
    "5-28": "St. Germain",
    "5-29": "St. Paul VI",
    "5-30": "St. Joan of Arc",
    "5-31": "The Visitation",

    // JUNE
    "6-1": "St. Justin Martyr",
    "6-2": "Sts. Marcellinus and Peter",
    "6-3": "St. Charles Lwanga",
    "6-4": "St. Francis Caracciolo",
    "6-5": "St. Boniface",
    "6-6": "St. Norbert",
    "6-7": "St. Robert",
    "6-8": "St. William of York",
    "6-9": "St. Ephrem",
    "6-10": "St. Joachima",
    "6-11": "St. Barnabas",
    "6-12": "St. John of Sahagun",
    "6-13": "St. Anthony of Padua",
    "6-14": "St. Elisha",
    "6-15": "St. Germaine",
    "6-16": "St. John Francis Regis",
    "6-17": "St. Joseph Cafasso",
    "6-18": "St. Gregory Barbarigo",
    "6-19": "St. Romuald",
    "6-20": "St. Alban",
    "6-21": "St. Aloysius Gonzaga",
    "6-22": "Sts. Thomas More & John Fisher",
    "6-23": "St. Joseph Cafasso",
    "6-24": "Nativity of John the Baptist",
    "6-25": "St. William",
    "6-26": "St. Josemaría Escrivá",
    "6-27": "St. Cyril of Alexandria",
    "6-28": "St. Irenaeus",
    "6-29": "Sts. Peter and Paul",
    "6-30": "First Martyrs of Rome",

    // JULY
    "7-1": "St. Junipero Serra",
    "7-2": "St. Oliver Plunkett",
    "7-3": "St. Thomas the Apostle",
    "7-4": "St. Elizabeth of Portugal",
    "7-5": "St. Anthony Zaccaria",
    "7-6": "St. Maria Goretti",
    "7-7": "St. Willibald",
    "7-8": "St. Gregory Grassi",
    "7-9": "St. Augustine Zhao Rong",
    "7-10": "St. Veronica",
    "7-11": "St. Benedict",
    "7-12": "St. John Jones",
    "7-13": "St. Henry",
    "7-14": "St. Kateri Tekakwitha",
    "7-15": "St. Bonaventure",
    "7-16": "Our Lady of Mount Carmel",
    "7-17": "St. Hedwig",
    "7-18": "St. Camillus",
    "7-19": "St. Arsenius",
    "7-20": "St. Apollinaris",
    "7-21": "St. Lawrence of Brindisi",
    "7-22": "St. Mary Magdalene",
    "7-23": "St. Bridget of Sweden",
    "7-24": "St. Sharbel",
    "7-25": "St. James the Apostle",
    "7-26": "Sts. Joachim and Anne",
    "7-27": "St. Titus Brandsma",
    "7-28": "St. Alphonsa",
    "7-29": "St. Martha",
    "7-30": "St. Peter Chrysologus",
    "7-31": "St. Ignatius of Loyola",

    // AUGUST
    "8-1": "St. Alphonsus Liguori",
    "8-2": "St. Peter Julian Eymard",
    "8-3": "St. Lydia",
    "8-4": "St. John Vianney",
    "8-5": "Dedication of St. Mary Major",
    "8-6": "The Transfiguration",
    "8-7": "St. Cajetan",
    "8-8": "St. Dominic",
    "8-9": "St. Teresa Benedicta",
    "8-10": "St. Lawrence",
    "8-11": "St. Clare of Assisi",
    "8-12": "St. Jane Frances de Chantal",
    "8-13": "Sts. Pontian and Hippolytus",
    "8-14": "St. Maximilian Kolbe",
    "8-15": "The Assumption of Mary",
    "8-16": "St. Stephen of Hungary",
    "8-17": "St. Joan of the Cross",
    "8-18": "St. Helena",
    "8-19": "St. John Eudes",
    "8-20": "St. Bernard of Clairvaux",
    "8-21": "St. Pius X",
    "8-22": "Queenship of Mary",
    "8-23": "St. Rose of Lima",
    "8-24": "St. Bartholomew",
    "8-25": "St. Louis",
    "8-26": "St. Joseph Calasanz",
    "8-27": "St. Monica",
    "8-28": "St. Augustine",
    "8-29": "Passion of St. John the Baptist",
    "8-30": "St. Jeanne Jugan",
    "8-31": "St. Raymond",

    // SEPTEMBER
    "9-1": "St. Giles",
    "9-2": "St. Ingrid",
    "9-3": "St. Gregory the Great",
    "9-4": "St. Rosalia",
    "9-5": "St. Teresa of Calcutta",
    "9-6": "St. Eleutherius",
    "9-7": "St. Cloud",
    "9-8": "Nativity of Mary",
    "9-9": "St. Peter Claver",
    "9-10": "St. Thomas of Villanova",
    "9-11": "St. Cyprian",
    "9-12": "Holy Name of Mary",
    "9-13": "St. John Chrysostom",
    "9-14": "Exaltation of the Holy Cross",
    "9-15": "Our Lady of Sorrows",
    "9-16": "St. Cornelius",
    "9-17": "St. Robert Bellarmine",
    "9-18": "St. Joseph of Cupertino",
    "9-19": "St. Januarius",
    "9-20": "St. Andrew Kim Taegon",
    "9-21": "St. Matthew",
    "9-22": "St. Lorenzo Ruiz",
    "9-23": "St. Pio of Pietrelcina",
    "9-24": "St. John Henry Newman",
    "9-25": "St. Finbar",
    "9-26": "Sts. Cosmas and Damian",
    "9-27": "St. Vincent de Paul",
    "9-28": "St. Wenceslaus",
    "9-29": "Sts. Michael, Gabriel, Raphael",
    "9-30": "St. Jerome",

    // OCTOBER
    "10-1": "St. Thérèse of Lisieux",
    "10-2": "Holy Guardian Angels",
    "10-3": "St. Theodora",
    "10-4": "St. Francis of Assisi",
    "10-5": "St. Faustina",
    "10-6": "St. Bruno",
    "10-7": "Our Lady of the Rosary",
    "10-8": "St. Pelagia",
    "10-9": "St. John Leonardi",
    "10-10": "St. Francis Borgia",
    "10-11": "St. John XXIII",
    "10-12": "St. Seraphim",
    "10-13": "St. Edward",
    "10-14": "St. Callistus",
    "10-15": "St. Teresa of Avila",
    "10-16": "St. Margaret Mary Alacoque",
    "10-17": "St. Ignatius of Antioch",
    "10-18": "St. Luke",
    "10-19": "Sts. Isaac Jogues & Companions",
    "10-20": "St. Paul of the Cross",
    "10-21": "St. Hilarion",
    "10-22": "St. John Paul II",
    "10-23": "St. John of Capistrano",
    "10-24": "St. Anthony Claret",
    "10-25": "St. Crispin",
    "10-26": "St. Peter of Alcantara",
    "10-27": "St. Evaristus",
    "10-28": "Sts. Simon and Jude",
    "10-29": "St. Narcissus",
    "10-30": "St. Alphonsus",
    "10-31": "St. Wolfgang",

    // NOVEMBER
    "11-1": "All Saints' Day",
    "11-2": "All Souls' Day",
    "11-3": "St. Martin de Porres",
    "11-4": "St. Charles Borromeo",
    "11-5": "St. Elizabeth",
    "11-6": "St. Leonard",
    "11-7": "St. Willibrord",
    "11-8": "St. Castorius",
    "11-9": "Dedication of St. John Lateran",
    "11-10": "St. Leo the Great",
    "11-11": "St. Martin of Tours",
    "11-12": "St. Josaphat",
    "11-13": "St. Frances Cabrini",
    "11-14": "St. Lawrence O'Toole",
    "11-15": "St. Albert the Great",
    "11-16": "St. Margaret of Scotland",
    "11-17": "St. Elizabeth of Hungary",
    "11-18": "Dedication of Peter and Paul",
    "11-19": "St. Mechtilde",
    "11-20": "St. Edmund",
    "11-21": "Presentation of Mary",
    "11-22": "St. Cecilia",
    "11-23": "St. Clement I",
    "11-24": "St. Andrew Dung-Lac",
    "11-25": "St. Catherine of Alexandria",
    "11-26": "St. John Berchmans",
    "11-27": "St. Francesco",
    "11-28": "St. Catherine Laboure",
    "11-29": "St. Saturninus",
    "11-30": "St. Andrew",

    // DECEMBER
    "12-1": "St. Eligius",
    "12-2": "St. Bibiana",
    "12-3": "St. Francis Xavier",
    "12-4": "St. John Damascene",
    "12-5": "St. Sabas",
    "12-6": "St. Nicholas",
    "12-7": "St. Ambrose",
    "12-8": "Immaculate Conception",
    "12-9": "St. Juan Diego",
    "12-10": "Our Lady of Loreto",
    "12-11": "St. Damasus I",
    "12-12": "Our Lady of Guadalupe",
    "12-13": "St. Lucy",
    "12-14": "St. John of the Cross",
    "12-15": "St. Virginia",
    "12-16": "St. Adelaide",
    "12-17": "St. Lazarus",
    "12-18": "St. Gatien",
    "12-19": "St. Anastasius",
    "12-20": "St. Dominic of Silos",
    "12-21": "St. Peter Canisius",
    "12-22": "St. Thomas",
    "12-23": "St. John of Kanty",
    "12-24": "St. Charbel",
    "12-25": "Nativity of the Lord",
    "12-26": "St. Stephen",
    "12-27": "St. John the Apostle",
    "12-28": "Holy Innocents",
    "12-29": "St. Thomas Becket",
    "12-30": "St. Egwin",
    "12-31": "St. Sylvester I",
  };

  // ==============================================================================
  // 3. CURATED DATA (This is where you add full bios manually over time)
  // ==============================================================================
  static final Map<String, SaintModel> _curatedSaintsData = {
    "Mary, Mother of God": const SaintModel(
      name: "Mary, Mother of God",
      isMajorFeast: true,
      bio:
          "The Theotokos, the Mother of Jesus Christ. Honored above all angels and saints, she is the model of perfect faith and obedience to God's will.",
      prayer:
          "Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.",
    ),
    "St. Joseph, Husband of Mary": const SaintModel(
      name: "St. Joseph",
      isMajorFeast: true,
      bio:
          "The foster father of Jesus and husband of the Blessed Virgin Mary. A just man of silence and strength, he is the patron of workers, fathers, and a happy death.",
      prayer:
          "St. Joseph, guardian of the Redeemer, protect our families and guide us in the path of life. Amen.",
    ),
    "St. Francis of Assisi": const SaintModel(
      name: "St. Francis of Assisi",
      isMajorFeast: true,
      bio:
          "Founder of the Franciscan Order. He abandoned a life of luxury to embrace Lady Poverty, seeing God in all creation. He bears the stigmata of Christ.",
      prayer:
          "Lord, make me an instrument of your peace. Where there is hatred, let me sow love. Amen.",
    ),
    "St. Patrick": const SaintModel(
      name: "St. Patrick",
      isMajorFeast: true,
      bio:
          "The Apostle of Ireland. Once a slave, he returned to convert a nation. Legend says he used the shamrock to explain the mystery of the Holy Trinity.",
      prayer:
          "Christ be with me, Christ within me, Christ behind me, Christ before me. Amen.",
    ),
    "St. Teresa of Calcutta": const SaintModel(
      name: "St. Teresa of Calcutta",
      isMajorFeast: true,
      bio:
          "Known to the world as Mother Teresa, she saw the face of Jesus in the poorest of the poor in the slums of India.",
      prayer:
          "Spread love everywhere you go. Let no one ever come to you without leaving happier. Amen.",
    ),
    "St. Anthony of Padua": const SaintModel(
      name: "St. Anthony of Padua",
      isMajorFeast: true,
      bio:
          "A powerful preacher and doctor of the Church. He is widely loved as the patron saint of lost things and lost souls.",
      prayer:
          "St. Anthony, gentle and powerful, help me find what is lost and draw me closer to Christ. Amen.",
    ),
    "St. Thérèse of Lisieux": const SaintModel(
      name: "St. Thérèse of Lisieux",
      isMajorFeast: true,
      bio:
          "The 'Little Flower' of Jesus. A Carmelite nun who taught that we can achieve holiness through doing small things with great love.",
      prayer:
          "O Jesus, my love, my vocation, at last I have found it. My vocation is Love! Amen.",
    ),
    "St. Valentine": const SaintModel(
      name: "St. Valentine",
      isMajorFeast: true,
      bio:
          "A Roman priest and physician who suffered martyrdom for ministering to Christians. He is the patron of love, young people, and happy marriages.",
      prayer:
          "St. Valentine, teach us to love selflessly and bravely in the name of Christ. Amen.",
    ),
    "St. Benedict": const SaintModel(
      name: "St. Benedict",
      isMajorFeast: true,
      bio:
          "The father of Western Monasticism. His 'Rule' established a way of life balanced between prayer and work (Ora et Labora).",
      prayer:
          "Gracious God, grant us the wisdom to prefer nothing to the love of Christ. Amen.",
    ),
    "St. Ignatius of Loyola": const SaintModel(
      name: "St. Ignatius of Loyola",
      isMajorFeast: true,
      bio:
          "Founder of the Jesuits. A soldier turned saint, he gave the Church the 'Spiritual Exercises' to discern God's will.",
      prayer:
          "Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will. Amen.",
    ),
  };
}
